function C = get_C(q1,q2,dq1,dq2,m1,m2,l1,l2)
%GET_C
%    C = GET_C(Q1,Q2,DQ1,DQ2,M1,M2,L1,L2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    03-May-2021 13:20:02

t2 = -q2;
t3 = q1+t2;
t4 = sin(t3);
C = reshape([0.0,-dq1.*l1.*l2.*m2.*t4,dq2.*l1.*l2.*m2.*t4,0.0],[2,2]);
