function M = get_M(q1,q2,m1,m2,l1,l2)
%GET_M
%    M = GET_M(Q1,Q2,M1,M2,L1,L2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    03-May-2021 13:20:02

t2 = -q2;
t3 = q1+t2;
t4 = cos(t3);
t5 = l1.*l2.*m2.*t4;
M = reshape([l1.^2.*(m1+m2),t5,t5,l2.^2.*m2],[2,2]);
