function G = get_G(q1,q2,m1,m2,l1,l2,g)
%GET_G
%    G = GET_G(Q1,Q2,M1,M2,L1,L2,G)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    03-May-2021 13:20:02

G = [g.*l1.*sin(q1).*(m1+m2);g.*l2.*m2.*sin(q2)];
