function P = autogen_energy_P(g,m_b,m_f,q2,q4)
%AUTOGEN_ENERGY_P
%    P = AUTOGEN_ENERGY_P(G,M_B,M_F,Q2,Q4)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    06-Oct-2021 10:57:35

P = g.*m_b.*q2+g.*m_f.*q4;
