function K = autogen_energy_T(dq1,dq2,dq3,dq4,m_b,m_f)
%AUTOGEN_ENERGY_T
%    K = AUTOGEN_ENERGY_T(DQ1,DQ2,DQ3,DQ4,M_B,M_F)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    06-Oct-2021 10:57:35

K = (m_b.*(dq1.^2+dq2.^2))./2.0+(m_f.*(dq3.^2+dq4.^2))./2.0;
