function M = autogen_M(m_b,m_f)
%AUTOGEN_M
%    M = AUTOGEN_M(M_B,M_F)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    06-Oct-2021 10:57:35

M = reshape([m_b,0.0,0.0,0.0,0.0,m_b,0.0,0.0,0.0,0.0,m_f,0.0,0.0,0.0,0.0,m_f],[4,4]);
