function C = autogen_C
%AUTOGEN_C
%    C = AUTOGEN_C

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    06-Oct-2021 10:57:35

C = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,4]);
